linioexp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('productos', views.ProductListView.as_view(), name='product-list'),
    path('productos/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('registro/', views.RegistrationView.as_view(), name='register'),
    path('add_to_cart/<int:product_pk>', views.AddToCartView.as_view(), name='add-to-cart'),
    path('remove_from_cart/<int:product_pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('carrito/', views.PedidoDetailView.as_view(), name='pedido-detail'),
    path('checkout/<int:pk>', views.PedidoUpdateView.as_view(), name='pedido-update'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('complete_payment/', views.CompletePaymentView.as_view(), name='complete-payment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Proveedor(models.Model):
    ruc = models.CharField(max_length=11)
    razon_social = models.CharField(max_length=20)
    telefono = models.CharField(max_length=9)

class Categoria(models.Model):
    codigo = models.CharField(max_length=4)
    nombre = models.CharField(max_length=50)

class Localizacion(models.Model):
  distrito = models.CharField(max_length=20)
  provincia = models.CharField(max_length=20)
  departamento = models.CharField(max_length=20)

  def get_full_name(self):
      return self.distrito + " - " + self.provincia + " - " + self.departamento

class Producto(models.Model):
    # Relaciones
    categoria = models.ForeignKey(
        'Categoria', on_delete=models.SET_NULL, null=True)
    proveedor = models.ForeignKey(
        'Proveedor', on_delete=models.SET_NULL, null=True)

    # Atributos
    nombre = models.CharField(max_length=20)
    descripcion = models.TextField()
    precio = models.FloatField()
    estado = models.CharField(max_length=3)
    descuento = models.FloatField(default=0)

    def get_precio_final(self):
        return self.precio * (1 - self.descuento)

    def sku(self):
        codigo_categoria = self.categoria.codigo.zfill(4)
        codigo_producto = str(self.id).zfill(6)

        return f'{codigo_categoria}-{codigo_producto}'


from django.contrib.auth.models import User

class Profile(models.Model):
    # Relacion con el modelo User de Django
    user = models.OneToOneField(User, on_delete=models.CASCADE) 

    # Atributos adicionales para el usuario
    documento_identidad = models.CharField(max_length=8)
    fecha_nacimiento = models.DateField()
    telefono = models.CharField(max_length=9)
    ## Opciones de genero
    MASCULINO = 'MA'
    FEMENINO = 'FE'
    NO_BINARIO = 'NB'
    GENERO_CHOICES = [
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
        (NO_BINARIO, 'No Binario')
    ]
    genero = models.CharField(max_length=2, choices=GENERO_CHOICES)

    def __str__(self):
        return self.user.get_username()

class Cliente(models.Model):
    # Relacion con el modelo Perfil
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    # Atributos especificos del Cliente
    preferencias = models.ManyToManyField(to='Categoria')

    def __str__(self):
        return f'Cliente: {self.user_profile.user.get_username()}'

class Colaborador(models.Model):
    # Relacion con el modelo Perfil
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    # Atributos especificos del Colaborador
    reputacion = models.FloatField()
    cobertura_entrega = models.ManyToManyField(to='Localizacion')

    def __str__(self):
        return f'Colaborador: {self.user_profile.user.get_username()}'

class Pedido(models.Model):
    # Relaciones
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    repartidor = models.ForeignKey('Colaborador', on_delete=models.SET_NULL, null=True)
    ubicacion = models.ForeignKey('Localizacion', on_delete=models.SET_NULL, null=True)

    # Atributos
    fecha_creacion = models.DateTimeField(auto_now=True)
    fecha_entrega = models.DateTimeField(blank=True, null=True)
    estado = models.CharField(max_length=3)
    direccion_entrega = models.CharField(max_length=100, blank=True, null=True)
    tarifa = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f'{self.cliente} - {self.fecha_creacion} - {self.estado}'

    def get_subtotal(self):
        detalles = self.detallepedido_set.all()
        total = 0
        for detalle in detalles:
            total += detalle.get_subtotal()
        return total
    
    def get_total(self):
        subtotal = self.get_subtotal()
        if type(self.tarifa) != float:
            self.tarifa = 0
        total = self.tarifa + subtotal
        return total

    def get_direccion_entrega(self):
        dir = self.ubicacion.get_full_name() + " -- " + self.direccion_entrega
        return dir

class DetallePedido(models.Model):
    # Relaciones
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)

    # Atributos
    cantidad = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.pedido.id} - {self.cantidad} x {self.producto.nombre}'

    def get_subtotal(self):
        return self.producto.get_precio_final() * self.cantidad

class ProductoImage(models.Model):
    product = models.ForeignKey('Producto', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to="products", null=True, blank=True)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Localizacion, Categoria

class UserForm(UserCreationForm):
    # django.contrib.auth.User attributes
    first_name = forms.CharField(max_length=150, required=False)
    last_name = forms.CharField(max_length=150, required=False)
    email = forms.EmailField(max_length=150)

    # Profile attributes
    documento_identidad = forms.CharField(max_length=8)
    fecha_nacimiento = forms.DateField()
    telefono = forms.CharField(max_length=9)
    ## Opciones de genero
    MASCULINO = 'MA'
    FEMENINO = 'FE'
    NO_BINARIO = 'NB'
    GENERO_CHOICES = [
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
        (NO_BINARIO, 'No Binario')
    ]
    genero = forms.ChoiceField(choices=GENERO_CHOICES)
    '''
    # Cliente attributes
    is_cliente = forms.BooleanField(required=False)
    preferencias = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False)

    # Colaborador attributes
    is_colaborador = forms.BooleanField(required=False)
    reputacion = forms.FloatField(required=False)
    cobertura_entrega = forms.ModelChoiceField(queryset=Localizacion.objects.all(), required=False)
    '''
    class Meta:
        model = User
        fields = ['username',
        'first_name',
        'last_name',
        'email',
        'documento_identidad',
        'fecha_nacimiento',
        'telefono',
        'genero'
        ]

main/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from .models import Producto
from django.views.generic import FormView, TemplateView, View, UpdateView
from django.urls import reverse_lazy 
from django.contrib.auth import login
from django.shortcuts import redirect
from django.db.models import F
from random import randint
from django.contrib import messages

# Importamos forms.py
from .forms import *
#Importamos las clases recien creadas
from .models import *

class HomePageView(TemplateView):

    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_products'] = Producto.objects.all()[:5]

        return context


class ProductListView(ListView):
    model = Producto

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            object_list = Producto.objects.filter(nombre__icontains=query)
            return object_list
        else:
            return Producto.objects.all()


class ProductDetailView(DetailView):
    model = Producto


class RegistrationView(FormView):
    template_name = 'registration/register.html'
    form_class = UserForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        # This methos is called when valid from data has been POSTed
        # It should return an HttpResponse

        # Create User
        username = form.cleaned_data['username']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']

        user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
        user.save()

        # Create Profile
        documento_identidad = form.cleaned_data['documento_identidad']
        fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
        telefono = form.cleaned_data['telefono']
        genero = form.cleaned_data['genero']

        user_profile = Profile.objects.create( user=user, documento_identidad=documento_identidad, fecha_nacimiento=fecha_nacimiento, telefono=telefono, genero=genero)
        user_profile.save()
        cliente = Cliente.objects.create(user_profile=user_profile)
        cliente.save()
        # Create Cliente if needed
        '''
        is_cliente = form.cleaned_data['is_cliente']
        if is_cliente:
            cliente = Cliente.objects.create(user_profile=user_profile)

            # Handle special attribute
            preferencias = form.cleaned_data['preferencias']
            preferencias_set = Categoria.objects.filter(pk=preferencias.pk)
            cliente.preferencias.set(preferencias_set)

            cliente.save()
        ''' 
        # Create Colaborador if needed
        '''
        is_colaborador = form.cleaned_data['is_colaborador']
        if is_colaborador:
            reputacion = form.cleaned_data['reputacion']
            colaborador = Colaborador.objects.create(user_profile=user_profile, reputacion=reputacion)

            # Handle special attribute
            cobertura_entrega = form.cleaned_data['cobertura_entrega']
            cobertura_entrega_set = Localizacion.objects.filter(pk=cobertura_entrega.pk)
            colaborador.cobertura_entrega.set(cobertura_entrega_set)

            colaborador.save()
        '''
        # Login the user
        messages.info(self.request, 'Registro completado, se envio tu informacion a tu email ' + email)
        login(self.request, user)
        return super().form_valid(form)
           


class AddToCartView(View):
    def get(self, request, product_pk):
        # Obten el cliente
        try:
            user_profile = Profile.objects.get(user=request.user)
        except:
            messages.info(request, 'Tienes que estar logueado para añadir a carrito')
            return redirect('home')

        cliente = Cliente.objects.get(user_profile=user_profile)
        # Obtén el producto que queremos añadir al carrito
        producto = Producto.objects.get(pk=product_pk)
        # Obtén/Crea un/el pedido en proceso (EP) del usuario
        pedido, _  = Pedido.objects.get_or_create(cliente=cliente, estado='EP')
        # Obtén/Crea un/el detalle de pedido
        detalle_pedido, created = DetallePedido.objects.get_or_create(
            producto=producto,
            pedido=pedido,
        )

        # Si el detalle de pedido es creado la cantidad es 1
        # Si no sumamos 1 a la cantidad actual
        if created:
            detalle_pedido.cantidad = 1
        else:
            detalle_pedido.cantidad = F('cantidad') + 1
        # Guardamos los cambios
        detalle_pedido.save()
        # Recarga la página
        return redirect(request.META['HTTP_REFERER'])

class RemoveFromCartView(View):
    def get(self, request, product_pk):
        # Obten el cliente
        try:
            user_profile = Profile.objects.get(user=request.user)
        except:
            messages.info(request, 'Tienes que estar logueado para remover de carrito')
            return redirect('home')
        cliente = Cliente.objects.get(user_profile=user_profile)
        # Obtén el producto que queremos añadir al carrito
        producto = Producto.objects.get(pk=product_pk)
        # Obtén/Crea un/el pedido en proceso (EP) del usuario
        pedido, _  = Pedido.objects.get_or_create(cliente=cliente, estado='EP')
        # Obtén/Crea un/el detalle de pedido
        detalle_pedido = DetallePedido.objects.get(
            producto=producto,
            pedido=pedido,
        )
        # Si la cantidad actual menos 1 es 0 elmina el producto del carrito
        # Si no restamos 1 a la cantidad actual
        if detalle_pedido.cantidad - 1 == 0:
            detalle_pedido.delete()
        else:
            detalle_pedido.cantidad = F('cantidad') - 1
            # Guardamos los cambios
            detalle_pedido.save()
        # Recarga la página
        return redirect(request.META['HTTP_REFERER'])


class RemoveFromCartView(View):
    def get(self, request, product_pk):
        # Obten el cliente
        try:
            user_profile = Profile.objects.get(user=request.user)
        except:
            messages.info(request, 'Tienes que estar logueado para remover de carrito')
            return redirect('home')
        cliente = Cliente.objects.get(user_profile=user_profile)
        # Obtén el producto que queremos añadir al carrito
        producto = Producto.objects.get(pk=product_pk)
        # Obtén/Crea un/el pedido en proceso (EP) del usuario
        pedido, _  = Pedido.objects.get_or_create(cliente=cliente, estado='EP')
        # Obtén/Crea un/el detalle de pedido
        detalle_pedido = DetallePedido.objects.get(
            producto=producto,
            pedido=pedido,
        )
        # Si la cantidad actual menos 1 es 0 elmina el producto del carrito
        # Si no restamos 1 a la cantidad actual
        if detalle_pedido.cantidad - 1 == 0:
            detalle_pedido.delete()
        else:
            detalle_pedido.cantidad = F('cantidad') - 1
            # Guardamos los cambios
            detalle_pedido.save()
        # Recarga la página
        return redirect(request.META['HTTP_REFERER'])


class PedidoDetailView(DetailView):
    model = Pedido

    def get(self, request, *args, **kwargs):
        try:
            user_profile = Profile.objects.get(user=request.user)
        except:
            # redirect here
            messages.info(request, 'Tienes que estar logueado para ver el carrito')
            return redirect('home')
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


    def get_object(self):
        # Obten el cliente
        #user_profile = Profile.objects.get(user=self.request.user)
        user_profile = Profile.objects.get(user=self.request.user)
        cliente = Cliente.objects.get(user_profile=user_profile)
        # Obtén/Crea un/el pedido en proceso (EP) del usuario
        try: 
            pedido = Pedido.objects.get(cliente=cliente, estado='EP')
        except:
            pedido,_ = Pedido.objects.get_or_create(cliente=cliente, estado='EP')
        return pedido

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if type(context['object']) != bool:
            context['detalles'] = context['object'].detallepedido_set.all()
            context['latest_products'] = Producto.objects.all()[:5]
            context['total_detalles'] = len(context['detalles'])
            context['subtotal'] = context['object'].get_subtotal()
        else:
            context['detalles']=[]
        return context

    def get_queryset(self):
        return Producto.objects.all()


class PedidoUpdateView(UpdateView):
    model = Pedido
    fields = ['ubicacion', 'direccion_entrega']
    success_url = reverse_lazy('payment')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        self.object = form.save(commit=False)
        # Calculo de tarifa
        self.object.tarifa = randint(5, 20)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        localizaciones = Localizacion.objects.all()
        elementos = []
        for localizacion in localizaciones:
            elementos.append({ "id":localizacion.id, "name":localizacion.get_full_name() })
        if type(context['object']) != bool:
            context['localizaciones'] = elementos
        else:
            context['localizaciones']=[]
        return context

class PaymentView(TemplateView): 
    template_name = "main/payment.html"

    def get_context_data(self, **kwargs):

main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <h3> Hola {{ user.get_username }} </h3>
    <p>
      <a href="{% url 'logout' %}">Cierra Sesion</a>
    </p>
    {% else %}
    <h3> Hola </h3>
    <p>
      <a href="{% url 'login' %}">Inicia Sesion</a> o
      <a href="{% url 'register' %}">Registrate</a>
    </p>
    {% endif %}

    <hr>

    {% if messages %}
        {% for message in messages %}
        <div class="notification {% if message.tags %}is-{{ message.tags }}{% endif %}">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}


    <h5> Ultimos productos </h5>
    <ul>
      {% for producto in latest_products %}
        <li>
          <a href="{% url 'product-detail' producto.pk %}">
            {{ producto.nombre }}
          </a>
          - {{ producto.precio }}
        </li>
      {% empty %}
        <li>Aun no hay productos disponibles.</li>
      {% endfor %}
    </ul>
    <hr>
    <ul>
      <li><a href="{% url 'product-list' %}">Ver Lista de Productos Completa</a></li>
    </ul>
{% endblock %}

main/templates/main/payment.html
{% extends "base.html" %}

{% block content %}
    <script src="https://www.paypal.com/sdk/js?client-id=Ae5CXtI8NNo5z-OxlwY2g0Ze740bIFqoDRwnUS-C2jhvEDvtGHTmLgMOnzA7FOSfAqxPoiUIcu-XP7ki"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <h3 class="Title"> Pago </h3>

    <h5>Subtotal: {{ pedido.get_subtotal }}</h5>
    <h5>Tarifa: {{ pedido.tarifa }}</h5>
    <h5>Precio total del pedido: {{ pedido.get_total }}</h5>
    <h5>Direccion de entrega: {{ pedido.get_direccion_entrega }}</h5>
    <br>
    <div class="block" id="paypal-button-container"></div>

    <!--Esto se agrego para testear que pasaria si se completa el pago-->
    <a href="{% url 'complete-payment' %}">Completar pago de prueba</a>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      var total = {{ pedido.get_total }}
      var complete_payment_url = {% url 'complete-payment' %}

      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: `${total}`
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            window.location.href = `${complete_payment_url}`;
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
{% endblock %}

main/templates/main/pedido_detail.html
{% extends "base.html" %} {% block content %}
<div class="row">
  <div class="col-sm"><h3 class="title">Carrito</h3></div>
  <div class="col-sm">
    <button
      type="button"
      id="btnmodal"
      class="btn btn-primary"
      data-toggle="modal"
      data-target="#exampleModalCenter"
    >
      Añadir más productos
    </button>
  </div>
</div>

<div class="block">
  <h5 class="subtitle">Información General</h5>
  <div class="content">
    <ul>
      <li>
        <strong>Cliente:</strong>
        {{object.cliente.user_profile.user.get_username }}
      </li>
      <li><strong>Fecha Creación:</strong> {{ object.fecha_creacion }}</li>
      <li><strong>Estado:</strong> {{ object.estado }}</li>
    </ul>
  </div>
</div>

<div class="block">
  <h5 class="subtitle">Detalle</h5>
  <div class="content">
    {% if total_detalles != 0 %}
    <ul>
      {% for detalle in detalles %}

      <div class="row" style="margin: 10px; diplay: inline-flex">
        <div class="col-3">
          <img
            src="{{ producto.images.first.image.url|default:'https://via.placeholder.com/128' }}"
            alt="Imagen no disponible"
          />
        </div>
        <div class="col-4" style="display: flex; align-items: center">
          {{ detalle.producto.nombre }}
        </div>
        <div class="col-4" style="display: flex; align-items: center">
          <div class="row" style="max-width: 150px">
            <a
              href="{% url 'add-to-cart' product_pk=detalle.producto.pk %}"
              class="button is-success"
              style="width: auto; text-decoration: none !important"
            >
              +
            </a>
            <p style="width: auto; margin: auto">{{ detalle.cantidad }}</p>
            <a
              href="{% url 'remove-from-cart' product_pk=detalle.producto.pk %}"
              class="button is-danger"
              style="width: auto; text-decoration: none !important"
            >
              -
            </a>
          </div>
        </div>
      </div>

      {% endfor %}
    </ul>
    <p style="font-size: 30px">Subtotal: {{ subtotal }}</p>
    <!--p> Total: {{ total }} </p-->
    {% endif %} {% if total_detalles == 0 %}
    <h3>No tienes productos en carrito</h3>
    {% endif %}
  </div>
</div>
{% if total_detalles != 0 %}
<a href="{% url 'pedido-update' pk=object.pk %}" class="button is-info">
  Checkout
</a>
{% endif %}
<hr />
<div class="content">
  <ul>
    <li><a href="{% url 'product-list' %}">Ver Lista de Productos</a></li>
    <li><a href="{% url 'home' %}">Volver al inicio</a></li>
  </ul>

  <p></p>
</div>

<div
  class="modal fade bd-example-modal-lg"
  id="exampleModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          Ultimos productos
        </h5>
        <button
          type="button"
          id="btnCloseHeader"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for producto in latest_products %}
        <div class="row" style="margin: 10px; diplay: inline-flex">
          <div class="col-3">
            <img
              src="{{ producto.images.first.image.url|default:'https://via.placeholder.com/128' }}"
              alt="Imagen no disponible"
            />
          </div>
          <div class="col-3" style="display: flex; align-items: center">
            <a
              href="{% url 'product-detail' producto.pk %}"
              style="
                text-decoration: none !important;
                color: #2874a6;
                font-size: 20px;
              "
            >
              {{ producto.nombre }}
            </a>
          </div>
          <div class="col-2" style="display: flex; align-items: center">
            <p
              style="
                text-decoration: none !important;
                color: #2874a6;
                font-size: 20px;
              "
            >
              {{ producto.precio }}
            </p>
          </div>
          <div class="col-2" style="display: flex; align-items: center">
            <a
              href="{% url 'add-to-cart' product_pk=producto.pk %}"
              class="button is-primary"
              style="text-decoration: none !important; font-size: 20px"
            >
              Añadir al carrito
            </a>
          </div>
        </div>
        {% empty %}
        <li>Aun no hay productos disponibles.</li>
        {% endfor %}
      </div>
      <div class="modal-footer">
        <button
          type="button"
          id="btnClose"
          class="btn btn-secondary"
          data-dismiss="modal"
        >
          Close
        </button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#btnmodal").click(function () {
    $("#exampleModalCenter").modal("show");
  });
  $("#btnClose").click(function () {
    console.log("band");
    $("#exampleModalCenter").modal("hide");
  });
  $("#btnCloseHeader").click(function () {
    console.log("band");
    $("#exampleModalCenter").modal("hide");
  });
</script>
{% endblock %}

main/templates/main/pedido_form.html
{% extends "base.html" %}

{% block content %}
    <h3 class="title"> Checkout </h3>
    <div class="block">
        <h5 class="subtitle"> Completa tus datos </h5>
        <form method="post" style="display:block;">
          {% csrf_token %}
          <div style="display:block;">
            <select name="ubicacion" required-id="id_ubicacion">
              {% for localizacion in localizaciones %}
                <option value= {{localizacion.id}} > {{localizacion.name}}</option>
              {% endfor %}
            </select>
            <input type="text" name="direccion_entrega">
            <input type="submit" value="Submit" class="button is-info">
          </div>
        </form>
        
    </div>
    <hr>
    <div class="content">
        <ul>
          <li><a href="{% url 'product-list' %}">Ver Lista de Productos</a></li>
          <li><a href="{% url 'home' %}">Inicio</a></li>
        </ul>
    </div>
{% endblock %}

main/templates/main/producto_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"
  />
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    integrity="undefined"
    crossorigin="anonymous"
  />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
    integrity="undefined"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://kit.fontawesome.com/4df7245c80.js"
    crossorigin="anonymous"
  ></script>
  <script src="sweetalert2.min.js"></script>
  <link rel="stylesheet" href="sweetalert2.min.css" />
  <head>
    <meta charset="utf-8" />
    <title>LinioExp</title>
  </head>
  <body>
    <style type="text/css">
      body {
        margin: 20px;
      }
      a {
        text-decoration: none !important;
        color: #2874a6;
        font-size: 20px;
      }
    </style>
    <h1>Linio Exp</h1>
    <hr />
    <h3>{{ object.nombre }}</h3>
    <ul>
      <li><strong>Precio:</strong> {{ object.precio }}</li>
      <li><strong>Descripcion:</strong> {{ object.descripcion }}</li>
      <li><strong>Categoria:</strong> {{ object.categoria.nombre }}</li>
    </ul>
    <hr />

    <div class="columns">
      {% for image in object.images.all %}
      <div class="column is-3">
        <figure class="image is-square">
          <a href="{{ image.image.url }}">
            <img src="{{ image.image.url }}" alt="No hay imagen disponible" />
          </a>
        </figure>
      </div>
      {% empty %}
      <div class="column content">
        <p>Aún no hay imágenes disponibles</p>
      </div>
      {% endfor %}
    </div>

    <div class="block">
      <a
        href="{% url 'add-to-cart' product_pk=object.pk %}"
        class="button is-primary"
      >
        Añadir al carrito
      </a>
      <a href="{% url 'pedido-detail' %}" class="button"> Ver carrito </a>
      <ul>
        <li><a href="{% url 'product-list' %}">Ver Lista de Productos</a></li>
        <li><a href="{% url 'home' %}">Inicio</a></li>
      </ul>
    </div>
  </body>
</html>